version: '3.8'
services:
    nginx:
        build:
            context: images/nginx
            args:
                username: ${USERNAME}
                domain: ${DOMAIN}
        container_name: magento_nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php
        volumes:
            - ./src:/var/www/html
            - ./images/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./images/nginx/conf/application.conf:/etc/nginx/application.conf
        networks:
            magento-network:
                aliases:
                    - ${DOMAIN}

    redis:
        image: redis:7
        container_name: magento_redis
        networks:
            - magento-network

    php:
        build:
            context: images/php
            dockerfile: Dockerfile-${PHP_VERSION}
            args:
                username: ${USERNAME}
                domain: ${DOMAIN}
                mercadopago_plugin_path: ${MERCADOPAGO_PLUGIN_PATH}
        container_name: magento_php
        volumes:
            - ./src:/var/www/html
            - ./sessions:/var/lib/php/sessions
            - ./credentials:/home/${USERNAME}/.composer
            - ./credentials:/var/www/html/var/composer_home
            # - ${MERCADOPAGO_PLUGIN_PATH}/src/MercadoPago:/var/www/html/app/code/MercadoPago
            # Next lines for php7.2
            - ./logs/php-fpm-error.log:/var/log/php-fpm/error-php-fpm.log
            - ./logs/php-fpm-access.log:/var/log/php-fpm/access-php-fpm.log
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - magento-network

    mailhog:
        image: mailhog/mailhog
        container_name: magento_mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - magento-network

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
        container_name: magento_elasticsearch
        environment:
          - node.name=es1
          - cluster.name=elasticsearch
          - bootstrap.memory_lock=true
          - ES_JAVA_OPTS=-Xms512m -Xmx512m
          - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - magento-network

    mysql:
        image: mariadb:10.4
        container_name: magento_mysql
        ports:
            - "3306:3306"
        volumes:
            - ./database/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234qwer
            MYSQL_DATABASE: magento
        networks:
            - magento-network

networks:
    magento-network:
