version: '3.8'
services:
    nginx:
        restart: always
        build:
            context: images/nginx
            args:
                username: ${USERNAME}
                domain: ${DOMAIN}
                cert_path: ${CERT_PATH}
                cert_key_path: ${CERT_KEY_PATH}
        container_name: magento_nginx
        ports:
            - 80:80
            - 443:443
        links:
            - php
        volumes:
            - ./src:/var/www/html
            - ./images/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./images/nginx/conf/application.conf:/etc/nginx/application.conf
            - ${CERT_PATH}:/certs/cert.pem
            - ${CERT_KEY_PATH}:/certs/cert.key
        networks:
            magento-network:
                aliases:
                    - ${DOMAIN}

    redis:
        restart: always
        image: redis:7
        container_name: magento_redis
        networks:
            - magento-network

    php:
        restart: always
        build:
            context: images/php
            dockerfile: Dockerfile-${PHP_VERSION}
            args:
                username: ${USERNAME}
                host_os: ${HOST_OS}
                domain: ${DOMAIN}
        container_name: magento_php
        volumes:
            - ./src:/var/www/html
            - ./sessions:/var/lib/php/sessions
            - ./credentials:/home/${USERNAME}/.composer
            - ../src/MercadoPago:/var/www/html/vendor/mercadopago/magento2-plugin/src/MercadoPago
            # Next lines for php7.2
            - ./logs/php-fpm-error.log:/var/log/php-fpm/error-php-fpm.log
            - ./logs/php-fpm-access.log:/var/log/php-fpm/access-php-fpm.log
        networks:
            - magento-network

    mailhog:
        restart: always
        image: mailhog/mailhog
        container_name: magento_mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - magento-network

    elasticsearch:
        restart: always
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
        container_name: elasticsearch
        environment:
          - node.name=es1
          - cluster.name=elasticsearch
          - bootstrap.memory_lock=true
          - ES_JAVA_OPTS=-Xms512m -Xmx512m
          - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - magento-network

    mysql:
        image: mysql:5.7
        container_name: prestashop_mysql
        ports:
            - "3306:3306"
        volumes:
            - ./database/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234qwer
        networks:
            - magento-network

networks:
    magento-network:
