version: '3.8'
services:
    nginx:
        restart: always
        build:
            context: images/nginx
            args:
                username: ${USERNAME}
                domain: ${DOMAIN}
                cert_path: ${CERT_PATH}
                cert_key_path: ${CERT_KEY_PATH}
        container_name: magento_nginx
        volumes:
            - ./src:/var/www/html
            - ./images/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./images/nginx/conf/application.conf:/etc/nginx/application.conf
            - ${CERT_PATH}:${CERT_PATH}
            - ${CERT_KEY_PATH}:${CERT_KEY_PATH}
        network_mode: host

    redis:
        restart: always
        image: redis:7
        container_name: magento_redis
        network_mode: host

    php:
        restart: always
        build:
            context: images/php
            dockerfile: Dockerfile-${PHP_VERSION}
            args:
                username: ${USERNAME}
                host_os: ${HOST_OS}
                domain: ${DOMAIN}
        container_name: magento_php
        volumes:
            - ./src:/var/www/html
            - ./sessions:/var/lib/php/sessions
            - ./credentials:/home/ubuntu/.composer
            - ./payment-magento-plugin:/var/www/html/app/code/MercadoPago/PaymentMagento
            # Next lines for php7.2
            - ./logs/php-fpm-error.log:/var/log/php-fpm/error-php-fpm.log
            - ./logs/php-fpm-access.log:/var/log/php-fpm/access-php-fpm.log
        network_mode: host

    mailhog:
        restart: always
        image: mailhog/mailhog
        container_name: magento_mailhog
        network_mode: host
